# Generated by Django 5.1.3 on 2024-12-09 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_country_options_alter_media_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'docx', 'mp4', 'mp3', 'flac', 'doc', 'pdf'])], verbose_name='File'),
        ),
    ]
