# Generated by Django 5.1.3 on 2024-12-09 06:33

import accounts.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_username_alter_useraddress_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'uniqeu': 'A user with that username already exists'}, max_length=150, null=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='verificationopt',
            name='code',
            field=models.IntegerField(validators=[accounts.utils.check_otp_code], verbose_name='Otp code'),
        ),
    ]
